POST http://localhost:3000/auth/refresh-tokens
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwLCJlbWFpbCI6ImpvaG4uNDQ0NDUyNDg0QGV4YW1wbGUuY29tIiwiaWF0IjoxNzU0ODIxODkzLCJleHAiOjE3NTQ4MjU0OTMsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.4XMjCTZR4YAFjzLA-V9GofFdRRdJp6SvRIs-wLh9zG4
{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwLCJpYXQiOjE3NTQ4MjE4OTMsImV4cCI6MTc1NDkwODI5MywiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.R6LcgOhcasPy-8mEqhoVw00ucY4HS1Y5vjng_juO1hw"
}