POST http://localhost:3000/tags
Content-Type: application/json

{
  "name": "nestjs",
  "slug": "nestjs",
  "description": "A progressive Node.js framework for building efficient server-side applications.",
  "featuredImageUrl": "https://example.com/images/nestjs-tag.png",
   "test": "test"
}
